# Generated by Django 4.0.1 on 2022-01-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
